"""Exports pristine character prototypes and EXP logo into C++ header files.

This script converts data/pristine_font_protos.json and data/real_exp_logo.png
into embedded C++ static arrays in src/cpp/src/ to avoid runtime filesystem
dependencies in the native DLL and test binaries.
"""

import json
import os
import sys
from typing import Dict, List, Tuple
import cv2
import numpy as np


def compute_vector_norm(float_map: List[float]) -> float:
  """Computes the L2 norm (zero-mean or raw) for template matching.

  Args:
    float_map: Raw float array representing normalized pixel values.

  Returns:
    The standard L2 Euclidean norm of the array.
  """
  arr = np.array(float_map, dtype=np.float32)
  return float(np.linalg.norm(arr))


def generate_pristine_font_header(json_path: str, output_path: str) -> None:
  """Generates pristine_font_protos.h from the JSON prototype dictionary.

  Args:
    json_path: Path to pristine_font_protos.json.
    output_path: Path to the target C++ header file.
  """
  with open(json_path, 'r', encoding='utf-8') as f:
    protos: Dict[str, Dict] = json.load(f)

  lines = [
      '// Copyright 2026 Artale Exp Project. All rights reserved.',
      '// Auto-generated by scripts/generate_cpp_headers.py. DO NOT EDIT.',
      '',
      '#ifndef ARTALE_EXP_CORE_PRISTINE_FONT_PROTOS_H_',
      '#define ARTALE_EXP_CORE_PRISTINE_FONT_PROTOS_H_',
      '',
      '#include <cstddef>',
      '',
      'namespace artale {',
      'namespace exp {',
      '',
      'struct PristinePrototype {',
      '  char character;',
      '  int width;',
      '  int height;',
      '  float norm;',
      '  const float* float_map;',
      '};',
      '',
  ]

  proto_var_names: List[Tuple[str, str, int, int, float]] = []

  for char, data in sorted(protos.items()):
    width: int = data['width']
    height: int = data['height']
    float_map: List[float] = np.array(data['float_map'], dtype=np.float32).flatten().tolist()
    norm: float = compute_vector_norm(float_map)

    # Sanitize identifier for C++ variable name
    char_code = ord(char)
    var_name = f'kProtoData_{char_code}'
    proto_var_names.append((char, var_name, width, height, norm))

    lines.append(f'// Prototype for \'{char}\' (width={width}, height={height})')
    lines.append(f'inline constexpr float {var_name}[{len(float_map)}] = {{')
    
    # Format 8 floats per line for readability and compact file size
    chunk_size = 8
    for i in range(0, len(float_map), chunk_size):
      chunk = float_map[i:i + chunk_size]
      formatted = ', '.join(f'{v:.6f}f' for v in chunk)
      comma = ',' if i + chunk_size < len(float_map) else ''
      lines.append(f'    {formatted}{comma}')
    lines.append('};')
    lines.append('')

  lines.append(f'inline constexpr size_t kNumPristinePrototypes = {len(proto_var_names)};')
  lines.append('')
  lines.append('inline const PristinePrototype kPristinePrototypes[kNumPristinePrototypes] = {')
  for char, var_name, width, height, norm in proto_var_names:
    escaped_char = '\\\'' if char == '\'' else ('\\\\' if char == '\\' else char)
    lines.append(
        f'    {{\'{escaped_char}\', {width}, {height}, {norm:.6f}f, {var_name}}},'
    )
  lines.append('};')
  lines.append('')
  lines.append('}  // namespace exp')
  lines.append('}  // namespace artale')
  lines.append('')
  lines.append('#endif  // ARTALE_EXP_CORE_PRISTINE_FONT_PROTOS_H_')
  lines.append('')

  os.makedirs(os.path.dirname(output_path), exist_ok=True)
  with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
  print(f'[SUCCESS] Wrote {len(proto_var_names)} pristine prototypes to {output_path}')


def generate_exp_logo_header(image_path: str, output_path: str) -> None:
  """Generates real_exp_logo_data.h from the grayscale EXP logo PNG image.

  Args:
    image_path: Path to real_exp_logo.png.
    output_path: Path to the target C++ header file.
  """
  img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
  if img is None:
    raise FileNotFoundError(f'Could not load logo image from {image_path}')

  height, width = img.shape
  total_pixels = height * width

  lines = [
      '// Copyright 2026 Artale Exp Project. All rights reserved.',
      '// Auto-generated by scripts/generate_cpp_headers.py. DO NOT EDIT.',
      '',
      '#ifndef ARTALE_EXP_CORE_REAL_EXP_LOGO_DATA_H_',
      '#define ARTALE_EXP_CORE_REAL_EXP_LOGO_DATA_H_',
      '',
      '#include <cstddef>',
      '#include <cstdint>',
      '',
      'namespace artale {',
      'namespace exp {',
      '',
      f'inline constexpr int kExpLogoWidth = {width};',
      f'inline constexpr int kExpLogoHeight = {height};',
      f'inline constexpr size_t kExpLogoTotalPixels = {total_pixels};',
      '',
      f'inline constexpr uint8_t kExpLogoGrayData[kExpLogoTotalPixels] = {{',
  ]

  flat_pixels = img.flatten().tolist()
  chunk_size = 16
  for i in range(0, total_pixels, chunk_size):
    chunk = flat_pixels[i:i + chunk_size]
    formatted = ', '.join(f'0x{val:02X}' for val in chunk)
    comma = ',' if i + chunk_size < total_pixels else ''
    lines.append(f'    {formatted}{comma}')

  lines.append('};')
  lines.append('')
  lines.append('}  // namespace exp')
  lines.append('}  // namespace artale')
  lines.append('')
  lines.append('#endif  // ARTALE_EXP_CORE_REAL_EXP_LOGO_DATA_H_')
  lines.append('')

  os.makedirs(os.path.dirname(output_path), exist_ok=True)
  with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
  print(f'[SUCCESS] Wrote {width}x{height} logo data to {output_path}')


def main() -> None:
  base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
  json_path = os.path.join(base_dir, 'data', 'pristine_font_protos.json')
  logo_path = os.path.join(base_dir, 'data', 'real_exp_logo.png')

  proto_header = os.path.join(base_dir, 'src', 'cpp', 'src', 'pristine_font_protos.h')
  logo_header = os.path.join(base_dir, 'src', 'cpp', 'src', 'real_exp_logo_data.h')

  generate_pristine_font_header(json_path, proto_header)
  generate_exp_logo_header(logo_path, logo_header)


if __name__ == '__main__':
  main()
